name: Cron CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * 1,5'

jobs:
  # == TEST == #
  test:
    name: (Check & Build &) Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust-toolchains:
          - 1.39.0
          - stable
          - beta
          - nightly
        latest-lockfile: [true, false]
        exclude:
          # This setup very often fails with a memory allocation failure on GH.
          - os: windows-latest
            rust-toolchains: 1.39.0
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        env:
          RUSTUP_UNPACK_RAM: 134217728  # Use 128 MiB rather than 500
        with:
          profile: minimal
          override: true
          toolchain: ${{ matrix.rust-toolchains }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Update the lockfile
        if: ${{ matrix.latest-lockfile }}
        uses: actions-rs/cargo@v1
        with:
          command: update

      - name: Cargo test (nightly)
        if: matrix.rust-toolchains == 'nightly'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: |
            --doc
            --no-default-features
            --features proc-macros
            --features nightly
            -- --nocapture

      - name: Cargo test
        if: matrix.rust-toolchains != 'nightly'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: |
            --doc
            --no-default-features
            --features proc-macros
            -- --nocapture

  # == TEST with MIRI == #
  # test-with-miri:
  #   name: Test with Miri
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       feature--alloc: ['', '--features alloc']
  #   steps:
  #     - name: Clone repo
  #       uses: actions/checkout@v2

  #     - name: Test with miri
  #       run: ./miri_test.sh --no-default-features ${{ matrix.feature--alloc }}
